In [ ]:
# fibonacci series
def fibo(number):
    n1,n2=0,1
    count=0
    if(number<=0):
        return " enter valid number"
    elif(number==1):
        return n1
    else:
        while(count<number):
            print(n1)
            nth=n1+n2
            n1=n2
            n2=nth
            count=count+1
number=int(input("enter a number:"))
fibo(number)

In [ ]:
# factorial of giveen number
def fact(number):
    if(number<=0):
        print("enter a valid number:")
    else:
        result=number*cal(number-1)
        print(result)
def cal(value):
    result=1
    while(value>0):
        result=result*value
        value=value-1
    return result
number=int(input('enter a number:'))  
fact(number) 

In [ ]:
# program for find area of circle
def area(radius):
    result=3.14*radius*radius
    print("area of circle is {} ".format(result))
radius=int(input("enter radius of circle"))
area(radius)

In [ ]:
# program for leap year
def leap(year):
    if(year%100==0):
        if(year%400==0):
            print("{} is a leap year".format(year))
        else: 
         print("{} is not a leap year".format(year))
    elif(year%4==0):
        print("{} is a leap year".format(year))
    else: 
         print("{} is not a leap year".format(year))    
year=int(input("enter a year:"))
leap(year)

In [2]:
# gcd of two numbers
def gcd(number1,number2):
    result=number1 if number1>number2 else number2
    count=result
    while(count>0):
        if((count%number1==0) and (count%number2==0)):
            print("gcd of {},{} is {}".format(number1,number2,count))
            break
        else:
            count=count+1   
number1=int(input("enter first number:"))
number2=int(input("enter second number:"))
gcd(number1,number2)

enter first number:3
enter second number:4
gcd of 3,4 is 12


In [8]:
# check weather given number is prime or not
def prime(number):
    if(number<=1):
        print("enter a valid number:")
    else:
        result=0
        count=2
        while(count<=number):
            if(number%count==0):
                result=result+1
                count=count+1
            else:
                count=count+1
        if(result>=2):
            print("{} is not a prime number".format(number))
        else:
            print("{} is a prime number".format(number))
number=int(input("enter a number:"))
prime(number)

enter a number:7
7 is a prime number


In [13]:
# print all prime numbers with in a range
def allprimes(number):
    if(number<=1):
        print("prime numbers are not possible {} in this range".format(number))
    else:
        for value in range(2,number):
            result,count=0,2
            while(count<=value):
                if(value%count==0):
                    result=result+1
                    count=count+1
                else:
                    count=count+1
            if(result<2):
                print(value)
number=int(input("enter a range value:"))
allprimes(number)
            
            
            
            
            
            

enter a range value:30
2
3
5
7
11
13
17
19
23
29


In [5]:
#check whether given number is strong number or not
#strong number means whose sum of all digist's factorial is equal to the number n(given number)
# example 145=1!+4!+5!=1+24+120=145 it is strong number.
def strong(number):
    
    while(number>=1):
        rem=number%10
        if(rem>1):
            result=0
            result=result+rem*fact(rem-1)
           
        else:
            result=result+1
        print(result)   
        number=number//10  
         
def fact(value):
    cal=1
    while(value>0):
        cal=cal*value
        value=value-1
    return cal         
number=int(input("enter a number:"))
strong(number)

enter a number:145
120
24
25


In [ ]:
# display calendar
import calendar as cal
year=int(input("enter year:"))
month=int(input("enter month:"))
print(cal.month(year,month))

In [ ]:
def sorting(lis):
    result=[]
    for word in lis:
        result=lis.sort()
        print(result)
count=0
lis=[]
number=int(input(" how many number of words you want sort:"))
while(count<=number):
    words=input('enter word:')
    lis.append(words)
    count=count+1
sorting(lis)

In [8]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [13]:
# logerthmic functions
import math
math.log(14)
math.log(14,10)# 14 is value and 10 base
math.log2(14)# 2 means base value
math.log10(14)
math.log1p(14)# it adds 1 value to 14 and find log(15)
math.log2p(14)# this type syntax is not possible

2.70805020110221

In [8]:
math.log(14)

2.6390573296152584

In [14]:
number=2
math.log(number+14)

2.772588722239781

In [48]:
#matrix multiplication program
import numpy as np
arr1=np.array([[2,3,4],[2,4,6],[1,2,3]])
arr2=np.array([[7,8,9],[3,5,8],[2,4,5]])
result=np.array([[0,0,0],[0,0,0],[0,0,0]])
first=arr1.shape
second=arr2.shape
if(first[1]==second[0]):
    for r in range(len(arr1)):
        for c in range(len(arr2[0])):
            for n in range(len(arr2)):
                result[r][c]=result[r][c]+arr1[r][n]*arr2[n][c]
    print('matrix multiplicat of two matrices\n',result,)
else:
    print("matrix multiplication is not possible")

matrix multiplicat of two matrices
 [[31 47 62]
 [38 60 80]
 [19 30 40]]


In [27]:
arr1=np.array([[2,3,4],[2,4,6]])
len(arr1)

2

In [56]:
list=[11,2,3]
list1=[2,3]
list2=[]
list2.append(list1)
list2.append(list)
print(list2)

[[2, 3], [11, 2, 3]]


In [39]:
result=np.empty([3,3])
result

array([[1.06134265e-312, 0.00000000e+000, 1.06395697e+224],
       [3.37923153e-057, 4.18300597e-062, 7.10488014e-038],
       [5.99118568e+174, 3.12007841e-085, 6.27207943e-310]])

In [58]:
# take input form user
rows=int(input('enter no rows:'))
columns=int(input('enter no columns'))
matrix=[[int(input()) for x in range(columns)]for y in range(rows)]
print(matrix)



enter no rows:2
enter no columns3
1
2
2
2
2
2
[[1, 2, 2], [2, 2, 2]]


In [10]:
#tcs program form nqt 2020
def arrange(str):
    new=""
    a=0
    e=0
    i=0
    o=0
    u=0
    for character in str:
        if(character=='a'):
            a=a+1
            
        elif(character=='e'):
            e=e+1
            
        elif(character=='i'):
            i=i+1
            
        elif(character=='o'):
            o=o+1
            
        elif(character=='u'):
            u=u+1
            
        else:
            new=new+character        
    count=a+e+i+o+u
    if(count>0):
        print('a:',a)
        print('e:',e)
        print('i:',i)
        print('o:',o)
        print('u:',u)
        print(new)
    else:
        print('0')
str=input("enter a string:")
arrange(str)

enter a string:hll cm
0


In [19]:
# tcs program from nqt 2020
# arrange ipl2020 cricket time table
print('   enter number of teams between 2 and 12')
print('--------------------------------------------')
number=2
team=[]
count=0
while(number<=12):
    result=input("enter team name:")
    if(result=='q'):
        break
    else:
        team.append(result)
        count=count+1
print(team)
print("**********************")
print('  create time table for your teams')
print('------------------------------------')
for i in team:
    for j in team:
        if(i==j):
            continue
        print(i,'*',j)
        
    
    

   enter number of teams between 2 and 12
--------------------------------------------
enter team name:naveen
enter team name:killer
enter team name:sai
enter team name:rupesh
enter team name:q
['naveen', 'killer', 'sai', 'rupesh']
**********************
  create time table for your teams
------------------------------------
naveen * killer
naveen * sai
naveen * rupesh
killer * naveen
killer * sai
killer * rupesh
sai * naveen
sai * killer
sai * rupesh
rupesh * naveen
rupesh * killer
rupesh * sai
